{% set name = "selfies" %}
{% set version = "1.0.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/selfies-{{ version }}.tar.gz
  sha256: 802d76edd9717d06cb994974ffd1224c14047fa5f802853666fd79bc7e99c949

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - python >=3.5
    - rdkit

test:
  imports:
    - selfies
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aspuru-guzik-group/selfies
  summary: SELFIES (SELF-referencIng Embedded Strings) is a general-purpose, sequence-based, robust representation of semantically constrained graphs.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
