{% set name = "selfies" %}
{% set version = "1.0.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/selfies-{{ version }}.tar.gz
  sha256: 30d635b83e3cda9307050ff9e83aa0d0d30b1e158c480cb5f8381eef07d5ca01

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - python >=3.5
    - rdkit

test:
  imports:
    - selfies
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aspuru-guzik-group/selfies
  summary: SELFIES (SELF-referencIng Embedded Strings) is a general-purpose, sequence-based, robust representation of semantically constrained graphs.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
