{% set name = "selfies" %}
{% set version = "2.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/selfies-{{ version }}.tar.gz
  sha256: 3398cb88aaa92bd2728286bdd16109c8aaebd5f30e7aa0550459fd64db351521

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - rdkit

test:
  imports:
    - selfies
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aspuru-guzik-group/selfies
  summary: SELFIES (SELF-referencIng Embedded Strings) is a general-purpose, sequence-based, robust representation of semantically constrained graphs.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
